name: CI

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - id: getMatrix
      run: |
        matrix=`node ./.github/workflows/ci/getTestJobs.mjs --ci`
        echo "::set-output name=matrix::$matrix"
    - run: echo ${{ steps.getMatrix.outputs.matrix }}
    outputs:
      matrix: ${{ steps.getMatrix.outputs.matrix }}

  test:
    needs: prepare
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
      fail-fast: false
    env:
      TEST_FILES: ${{ matrix.TEST_FILES }}
      TEST_INSPECT: ${{ matrix.TEST_INSPECT }}
    runs-on: ${{ matrix.os }}
    name: '${{ matrix.jobName }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm exec playwright install chromium # Needed for Windows/MacOS
      - run: pnpm run build

      - name: Run tests
        run: ${{ matrix.jobCmd }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Upload screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: 'screenshots'
          path: |
            **/test-screenshot-expect.png
            **/test-screenshot-actual.png
            **/test-screenshot-differ.png
