name: Docs
on:
  push:
    # We only run this GitHub action upon new commits to `master`
    branches:
      - master
    # We only run this GitHub action if there are changes in the `docs/` directory
    paths:
      - docs/**
      - libframe
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        # `yarn install` will checkout the git submodule `libframe/`
        run: |
          yarn install

      - name: Build
        run: |
          yarn docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/dist/client
          # Remove previous build files
          clean: true
          # Do not remove the `.nojekyll` file: we have manually added an empty `.nojekyll` file at the root of the `gh-pages` branch and we don't want having to re-create it after each build.
          clean-exclude: |
            .nojekyll
